### ISSUE TITLE
Custom Field values updates not Appear on Export

### ISSUE THREAD

**Issue by mclayton1121** [trapias/TrelloExport#34] opened 2018-04-03 13:59 UTC
Prior to update when exported custom fields values appear.  Now when export only see values for custom fields entered prior to 3/27/18.  Anything entered on or after not exported.

**Comment by mikekonikoff** [comment] 2018-04-06 15:25
Same for me, except the cutoff date is 3/2. Cards created after that date have custom fields, but the values won't export.

**Comment by trapias** [comment] 2018-04-07 10:46
Custom fields not working, duplicate of #31

**Closed by trapias** 2018-04-07 10:46 UTC
