### ISSUE TITLE
Problem with your extention like: #&32 etc....

### ISSUE THREAD

**Issue by Stratboy1965** [trapias/TrelloExport#44] opened 2018-05-04 13:04 UTC
We improve a problem with your extention. We have code like #&32;#&42;#&52... 
![trello export](https://user-images.githubusercontent.com/38981224/39628531-61adf478-4f77-11e8-8ebe-910f99c47944.PNG)

**Comment by trapias** [comment] 2018-05-04 21:43
Duplicate of #43 - encoding issue

**Closed by trapias** 2018-05-04 21:43 UTC
Labels: duplicate
