### ISSUE TITLE
Setting the value of 'TrelloExportListDone' exceeded the quota.

### ISSUE THREAD

**Issue by mordrax** [trapias/TrelloExport#59] opened 2019-01-31 22:40 UTC
Trying to export with default parameters, or filtering by one small list of 1-2 cards gets me errors like below. It doesn't matter if I have anything in the Done input box or whether I've applied a filter.

Chrome Version 71.0.3578.98 (Official Build) (64-bit)
TrelloExport 1.9.61

```
trelloexport.js:739 Uncaught DOMException: Failed to set the 'TrelloExportListDone' property on 'Storage': Setting the value of 'TrelloExportListDone' exceeded the quota.
    at HTMLButtonElement.<anonymous> (chrome-extension://kmmnaeamjfdnbhljpedgfchjbkbomahp/trelloexport.js:739:43)
(anonymous) @ trelloexport.js:739
3trelloexport.js:855 Uncaught DOMException: Failed to set the 'TrelloExportSelectedColumns' property on 'Storage': Setting the value of 'TrelloExportSelectedColumns' exceeded the quota.
    at Object.onSelectAll (chrome-extension://kmmnaeamjfdnbhljpedgfchjbkbomahp/trelloexport.js:855:58)
    at Multiselect.updateSelectAll (chrome-extension://kmmnaeamjfdnbhljpedgfchjbkbomahp/lib/bootstrap-multiselect/bootstrap-multiselect.js:1294:34)
    at new Multiselect (chrome-extension://kmmnaeamjfdnbhljpedgfchjbkbomahp/lib/bootstrap-multiselect/bootstrap-multiselect.js:172:14)
    at HTMLSelectElement.<anonymous> (chrome-extension://kmmnaeamjfdnbhljpedgfchjbkbomahp/lib/bootstrap-multiselect/bootstrap-multiselect.js:1395:24)
    at Function.each (chrome-extension://kmmnaeamjfdnbhljpedgfchjbkbomahp/lib/jquery-2.1.0.min.js:2:2877)
    at o.fn.init.each (chrome-extension://kmmnaeamjfdnbhljpedgfchjbkbomahp/lib/jquery-2.1.0.min.js:2:818)
    at o.fn.init.$.fn.multiselect (chrome-extension://kmmnaeamjfdnbhljpedgfchjbkbomahp/lib/bootstrap-multiselect/bootstrap-multiselect.js:1389:21)
    at initializeModal (chrome-extension://kmmnaeamjfdnbhljpedgfchjbkbomahp/trelloexport.js:852:31)
    at t.onOpen (chrome-extension://kmmnaeamjfdnbhljpedgfchjbkbomahp/trelloexport.js:719:13)
    at HTMLDivElement.o (chrome-extension://kmmnaeamjfdnbhljpedgfchjbkbomahp/lib/tingle.min.js:1:4384)
```

**Comment by trapias** [comment] 2019-02-19 21:28
@mordrax will look into this asap

**Comment by trapias** [comment] 2019-02-19 21:43
@mordrax strange error... are you short of disk space? Many tabs open in Chrome? Did you try the "clean localstorage" button?

**Comment by mordrax** [comment] 2019-02-19 22:37
@trapias Definitely not short of disk space, memory, etc. I did some googling and cleared out localstorage. I eventually managed to get this to work by duplicating the board and deleting most of the lists that I didn't care about. Our trello board is ~100MB including attachments, but it doesn't matter how small a set of cards I choose, always the same error.

**Comment by trapias** [comment] 2019-03-05 18:05
@mordrax TE loading mechanism should be improved (see also #29, I'm closing this issue since the problem is the same): it does not handle properly large amount of data.

As you read on the [wiki](https://github.com/trapias/TrelloExport/wiki/KnownIssues)...

I'm working to solve the issue, but don't expect a solution anytime soon: if TrelloExport is not enough for you, please check out-of-browser solutions like [Bridge24](https://bridge24.com/trello/?afmc=1w).

Regards,
Alberto.

**Closed by trapias** 2019-03-05 18:05 UTC
Labels: bug, duplicate
